<?php if ($url) : ?>
    <meta property="og:url" content="<?php echo $url ?>" />
<?php endif ?>
<?php if ($type) : ?>
    <meta property="og:type" content="<?php echo $type ?>" />
<?php endif ?>
<?php if ($title) : ?>
    <meta property="og:title" content="<?php echo $title ?>" />
<?php endif ?>
<?php if ($description) : ?>
    <meta property="og:description" content="<?php echo $description ?>" />
<?php endif ?>
<?php if ($image) : ?>
    <meta property="og:image" content="<?php echo $image ?>" />
<?php endif ?>